### ISSUE TITLE
Some issues found during initial test

### ISSUE THREAD

**Issue by chrjorgensen** [SeidenGroup/pfgrep#3] opened 2024-12-07 22:53 UTC
Hello Allan and Calvin.

I just watched the `Code for i Fridays - Dec. 6` recording where `pfgrep` was introduced and demoed - and although I reckon it is in an early state, I gave it a spin on my IBM i 7.3 partition to check it out. I was curious to see if CCSID was handled correctly, since we have had a lot of CCSID issues in the Code for IBM i extension... 😄 

I installed `pfgrep` from the Seiden repositories using `yum` and it worked right away, when I searched for the Danish characters 'ÆØÅ'! 👏 

However, I also saw some issues in the output:

```
→ pfgrep -r 'Æ' /qsys.lib/nccj.lib
opening /qsys.lib/nccj.lib/AUDIT00001.FILE/AUDIT00001.MBR: Not a source physical file member
/qsys.lib/nccj.lib/CCSIDNONE.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE2.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE3.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE4.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE5.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSID280.FILE/MEMBER.MBR:This line has the danish characters æøåÆØÅ
/qsys.lib/nccj.lib/CCSID280.FILE/MEMBER.MBR:
hex 25 = green, underline, reverse-image æøåÆØÅ xxx
/qsys.lib/nccj.lib/CCSID37.FILE/MEMBER.MBR:This line has the danish characters æøåÆØÅ
opening /qsys.lib/nccj.lib/CODE4ILOG.FILE/CODE4ILOG.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/COLCOL.FILE/PART000001.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/COLCOL.FILE/PART000002.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/CBX959H.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/CL_IFS.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/EXAMPLE1.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/GET_SNTP.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/GET_SNTP2.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/HELLO.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/QSTRUPNCCJ.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/RPG.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/RTVSRCMBRD.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TEST.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTBOL73.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTCLLE.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTCODE.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTDTAARA.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTSQL.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TESTSQLRPG.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/EVFEVENT.FILE/TEST2.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/FTPPIPE.FILE/FTPPIPE.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/LICINF.FILE/LICINF.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/MBRCCSID.FILE/MBRCCSID.MBR: Operation not supported on socket
opening /qsys.lib/nccj.lib/M05_FC_OUT.FILE/M05_FC_OUT.MBR: Not a source physical file member
opening /qsys.lib/nccj.lib/M05_SRC.FILE/M05_SRC.MBR: Not a source physical file member
/qsys.lib/nccj.lib/NCCJTEST.FILE/ABC#.MBR:Dette er filen med æøåÆØÅ og det hele...!
/qsys.lib/nccj.lib/NCCJTEST.FILE/HEXCODES2.MBR:
hex 25 = green, underline, reverse-image æøåÆØÅ
/qsys.lib/nccj.lib/NCCJTEST.FILE/MEMBER.MBR:/include NCCJTESTÆ/NCCJTESTÆ,DUMMY
QDBRTVFD: CPF5715
IOT/Abort trap (core dumped)
```

The most obvious is the dump in `QDBRTVFD` with error `CPF5715`. This happens with file `NCCJTESTÅ` which is probably because the character `Å` is the Danish variant of `$`. Seems like it doesn't like filenames ending in `$`? In CCSID 277 (Danish) the characters `ÆØÅ` are the variants of characters `#@$` in CCSID 37.

Also all the lines with message `Not a source physical file member` shouldn't be there, right? The files are datafiles, not source physical files, and I would expect them not to be searched - or to have an option for searching source physical files only?

Another issue is the message `Operation not supported on socket` - the file `MBRCCSID` is a logical file or more precisely a SQL view.

Keep up the great work - I really appreciate what you all in Seiden Group brings to the IBM i open source community!

Best regards,
Christian

**Comment by NattyNarwhal** [comment] 2024-12-07 23:04
> I installed pfgrep from the Seiden repositories using yum and it worked right away, when I searched for the Danish characters 'ÆØÅ'! 👏

While I haven't tested non-37 encodings extensively, I've tried to write it with them in mind - a lot of other alternative approaches to doing searches I could have tried would have broken down, especially for DBCS.

> The most obvious is the dump in QDBRTVFD with error CPF5715. This happens with file NCCJTESTÅ which is probably because the character Å is the Danish variant of $. Seems like it doesn't like filenames ending in $? In CCSID 277 (Danish) the characters ÆØÅ are the variants of characters #@$ in CCSID 37.

This is a bit weird - my best guess is the PASE encoding might be set to something that doesn't have the characters in your EBCDIC encoding, so the conversion for the path names breaks. Try doing `export LC_ALL=EN_US` (or I guess `LC_ALL=DA_DK` in your case), which should be UTF-8 encodings.

> Also all the lines with message Not a source physical file member shouldn't be there, right? The files are datafiles, not source physical files, and I would expect them not to be searched - or to have an option for searching source physical files only?

It only searches for source PFs, but I don't see a reason why it couldn't search non-source files other than being overly defensive with checks.

> Another issue is the message Operation not supported on socket - the file MBRCCSID is a logical file or more precisely a SQL view.

It should probably check for these, yes. You can't read these via POSIX style I/O which we currently do. I was looking into using record I/O directly (since it'd be a way to get sequence/date, as POSIX I/O strips these for source files) which might be able to read LFs, but it does involve wrapping the ILE functions and might incur some nasty performance issues.

**Comment by chrjorgensen** [comment] 2024-12-07 23:35
> This is a bit weird - my best guess is the PASE encoding might be set to something that doesn't have the characters in your EBCDIC encoding, so the conversion for the path names breaks. Try doing `export LC_ALL=EN_US` (or I guess `LC_ALL=DA_DK` in your case), which should be UTF-8 encodings.

My PASE SSH session already has `LC_ALL=EN_US.UTF-8` - and running `LC_ALL=DA_DK pfgrep -r 'Æ' /qsys.lib/nccj.lib` does not change anything.

When I run `find /qsys.lib/nccj.lib -maxdepth 1 -type d` I see the files - including file `N$`:

```
...
/qsys.lib/nccj.lib/M05_FC_OUT.FILE
/qsys.lib/nccj.lib/M05_SRC.FILE
/qsys.lib/nccj.lib/NCCJTEST.FILE
/qsys.lib/nccj.lib/NCCJTEST$.FILE
/qsys.lib/nccj.lib/NCCJTEST#.FILE
/qsys.lib/nccj.lib/NCCJTEST##.FILE
/qsys.lib/nccj.lib/NCCJTEST@.FILE
/qsys.lib/nccj.lib/NONDESC.FILE
/qsys.lib/nccj.lib/QCLSRC.FILE
/qsys.lib/nccj.lib/QCLSRC2.FILE
...
```

And I can list the members in `NCCJTEST$`:

```
→ ls /qsys.lib/nccj.lib/nccjtest\$.file
MEMBER#.MBR  'MEMBER$.MBR'
```

> It only searches for source PFs, but I don't see a reason why it couldn't search non-source files other than being overly defensive with checks.

If it only searches for source physical files, shouldn't these files be omitted and not output at all? I can see that there is a test in the QDBRTVFD for the *SRC attribute, but does this work? Why are datafiles and LF's included in the output?

**Comment by NattyNarwhal** [comment] 2024-12-08 02:23
Hmm, I'm trying to reproduce this and I can't seem to:

```
$ cl "chgjob ccsid(277)"
$ system addpfm calvin/qclsrc testÅ
CPC7305: Member TESTÅ added to file QCLSRC in CALVIN.
calvin@SEIDEN72:~/pfgrep$ system addpfm calvin/qclsrc testÆ
CPC7305: Member TESTÆ added to file QCLSRC in CALVIN.
calvin@SEIDEN72:~/pfgrep$ system addpfm calvin/qclsrc testØ
CPC7305: Member TESTØ added to file QCLSRC in CALVIN.
$ ./pfgrep -r thing /QSYS.LIB/CALVIN.LIB/QCLSRC.FILE
[no crash]
$ ls /QSYS.LIB/CALVIN.LIB/QCLSRC.FILE
'HELLO$.MBR'  LOOP.MBR  TEST#.MBR  'TEST$.MBR'  TEST@.MBR
```

And from `DSPFD`:

```
$ # as CCSID 277...
$ system "DSPFD FILE(calvin/qclsrc) TYPE(*MBRLIST)"
 5770SS1 V7R2M0  140418               Display File Description                                  12/07/24  21:04:17       Page    1
   File  . . . . . . . . . . . : QCLSRC
     Library . . . . . . . . . : CALVIN
   Type of information . . . . : *MBRLIST
   File attributes . . . . . . : *ALL
   System  . . . . . . . . . . : *LCL
   Processor . . . . . . . . . : IBM AS/400 Display File Description Processor
 File . : QCLSRC       Library . : CALVIN       Type of file . : Physical *SRC             Auxiliary Storage Pool ID . : 00001
                                           Member List
                              Source Creation    Last Change                  Deleted
  Member           Size        Type  Date       Date     Time      Records    Records
  HELLOÅ                 8192        12/07/24 12/07/24 17:43:53          1          0
    Text:
  LOOP                   8192 CLP    01/26/22 01/26/22 14:40:00         16          0
    Text:
  TESTÅ                  8192        12/07/24 12/07/24 20:48:05          0          0
    Text:
  TESTÆ                  8192        12/07/24 12/07/24 20:54:37          0          0
    Text:
  TESTØ                  8192        12/07/24 12/07/24 20:54:43          0          0
    Text:
  Total number of members  . . . . . . . . . :                 5
  Total number of members not available  . . :                 0
  Total records  . . . . . . . . . . . . . . :                17
  Total deleted records  . . . . . . . . . . :                 0
  Total of member sizes  . . . . . . . . . . :             40960
$ cl "chgjob ccsid(37)"
$ system "DSPFD FILE(calvin/qclsrc) TYPE(*MBRLIST)"
 5770SS1 V7R2M0  140418               Display File Description                                  12/07/24  21:04:29       Page    1
   File  . . . . . . . . . . . : QCLSRC
     Library . . . . . . . . . : CALVIN
   Type of information . . . . : *MBRLIST
   File attributes . . . . . . : *ALL
   System  . . . . . . . . . . : *LCL
   Processor . . . . . . . . . : IBM AS/400 Display File Description Processor
 File . : QCLSRC       Library . : CALVIN       Type of file . : Physical *SRC             Auxiliary Storage Pool ID . : 00001
                                           Member List
                              Source Creation    Last Change                  Deleted
  Member           Size        Type  Date       Date     Time      Records    Records
  HELLO$                 8192        12/07/24 12/07/24 17:43:53          1          0
    Text:
  LOOP                   8192 CLP    01/26/22 01/26/22 14:40:00         16          0
    Text:
  TEST$                  8192        12/07/24 12/07/24 20:48:05          0          0
    Text:
  TEST#                  8192        12/07/24 12/07/24 20:54:37          0          0
    Text:
  TEST@                  8192        12/07/24 12/07/24 20:54:43          0          0
    Text:
  Total number of members  . . . . . . . . . :                 5
  Total number of members not available  . . :                 0
  Total records  . . . . . . . . . . . . . . :                17
  Total deleted records  . . . . . . . . . . :                 0
  Total of member sizes  . . . . . . . . . . :             40960
```

That said, the error handling from `QDBRTVFD` isn't very good, so I'll probably fix that.

> If it only searches for source physical files, shouldn't these files be omitted and not output at all? I can see that there is a test in the QDBRTVFD for the *SRC attribute, but does this work? Why are datafiles and LF's included in the output?

It checks if it's a `*FIILE` from looking at a ` stat` call, tries to process it, then bails when it's not a source file. Where the check is is misplaced when you think about it further.

**Comment by NattyNarwhal** [comment] 2024-12-08 22:37
Good news from the future:

```
$ ./pfgrep -i TX /QSYS.LIB/QIWS.LIB/QCUSTCDT.FILE/CUSTCDT.MBR 
938472Henning G K4859 Elm Ave DallasTX7521750003003700000000
593029WilliamsE D485 SE 2 Ave DallasTX7521802001002500000000
```

I'm going to try to clean up error handling - a lot of it is at the boundaries of using POSIX I/O for physical files...

If there's an easier way to reproduce the path issues you're having, let me know.

**Comment by chrjorgensen** [comment] 2024-12-09 16:35
@NattyNarwhal Thanks for testing CCSID 277 - but your test is about members with special characters in the name, where my issue is with file objects having special characters in the name.

There is a distinct difference here: File objects are validated using the QDBRTVFD API... and maybe the root cause? Testing file objects with special characters may reproduce the issue on your server?

I pulled the latest commits and ran `make` and `make install`, and now I get a different output:

```
...
/qsys.lib/nccj.lib/NCCJTEST.FILE/HEXCODES2.MBR:
hex 25 = green, underline, reverse-image æøåÆØÅ
/qsys.lib/nccj.lib/NCCJTEST.FILE/MEMBER.MBR:/include NCCJTESTÆ/NCCJTESTÆ,DUMMY
QDBRTVFD: CPF5715
get_pf_info(/qsys.lib/nccj.lib/NCCJTEST$.FILE/MEMBER$.MBR): Couldn't get record length
get_pf_info(/qsys.lib/nccj.lib/NCCJTEST$.FILE/MEMBER#.MBR): Couldn't get record length
QDBRTVFD: CPF5715
get_pf_info(/qsys.lib/nccj.lib/NCCJTEST#.FILE/$EN2.MBR): Couldn't get record length
get_pf_info(/qsys.lib/nccj.lib/NCCJTEST#.FILE/$IGEN.MBR): Couldn't get record length
get_pf_info(/qsys.lib/nccj.lib/NCCJTEST#.FILE/ABCDE.MBR): Couldn't get record length
...
```

So it's continuing now - but still have problems... 😃

**Comment by NattyNarwhal** [comment] 2024-12-09 17:09
Ah, I'm testing files and that does have problems. I think the big problem is the `/QSYS.LIB` virtual filesystem has that mapping, but `Qp0lCvtPathToQSYSObjName` seems unaware of this mapping and converts them to those characters, which do exist in the target EBCDIC encoding. I'm wondering how this can be handled in a general way, hopefully without hardcoding. The [documentation on this](https://www.ibm.com/docs/en/i/7.5?topic=qsyslib-path-names-in-file-system) leaves more questions than answers.

**Comment by NattyNarwhal** [comment] 2024-12-09 17:48
The horrible answer I think is just force 37 to all EBCDIC path names instead of using the system EBCDIC CCSID. We use `iconv` directly for user data and conversions we do with user data is just path names (which are coerced to 37) and exception IDs (which should be the same in all EBCDIC encodings). Can you try the latest commit and see if it works for you? My quick testing shows it seems to solve it.

**Comment by chrjorgensen** [comment] 2024-12-10 08:04
@NattyNarwhal I can confirm the latest commit [781faf8](https://github.com/SeidenGroup/pfgrep/commit/781faf845f225165a7d0f945218f46abeef24fbe) fixes all my issues! 🎉 

No more `CPF5715` or filename issues, no more record length issues:

```
→ time pfgrep -r 'ø' /qsys.lib/nccj.lib
/qsys.lib/nccj.lib/CCSIDNONE.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE2.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE3.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE4.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSIDNONE5.FILE/MEMBER1.MBR:ABC æøåÆØÅ!
/qsys.lib/nccj.lib/CCSID280.FILE/MEMBER.MBR:This line has the danish characters æøåÆØÅ
/qsys.lib/nccj.lib/CCSID280.FILE/MEMBER.MBR:
hex 25 = green, underline, reverse-image æøåÆØÅ xxx
/qsys.lib/nccj.lib/CCSID37.FILE/MEMBER.MBR:This line has the danish characters æøåÆØÅ
/qsys.lib/nccj.lib/NCCJTEST.FILE/ABC#.MBR:Dette er filen med æøåÆØÅ og det hele...!                                                
/qsys.lib/nccj.lib/NCCJTEST.FILE/HEXCODES2.MBR:
hex 25 = green, underline, reverse-image æøåÆØÅ

real    0m0.506s
user    0m0.135s
sys     0m0.002s
```

As I see it, you're not forcing CCSID 37 and it is not a horrible answer! You are merely handling the CCSID tags between PASE and API's. CCSID is never fun and causes a lot of issues and confusion - let's go for IBM i UTF-8, like Linux! 😍 

Thanks for the quick fix! I will follow this tool closely, always great to see improvements in speed and function compared to the built-in tools. 😃

**Comment by NattyNarwhal** [comment] 2024-12-10 15:52
I'll close the issue then and provide an updated build.

**Closed as completed by NattyNarwhal** 2024-12-10 15:52 UTC
